name: AOC
version: '1.0'
license: AllRightsReserved
dependencies:
- containers
- base
- parsec
- mtl
- array
- hedgehog
- bytestring
- ansi-terminal
executables:
  AOC:
    main: Main.hs
    ghc-options:
      - -ddump-to-file 
      - -ddump-hi
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -O2
    other-modules:
      - AOC1
      - AOC2
      - AOC3
      - AOC4
      - AOC5
      - AOC6
      - AOC7
      - AOC8
      - AOC9
      - AOC10
data-files:
- example.txt
stability: experimental
