name: AOC
version: '1.0'
license: AllRightsReserved
dependencies:
- ansi-terminal
- apecs
- array
- base
- bytestring
- containers
- directory
- hedgehog
- HUnit
- json
- lens
- lens-aeson
- logict
- mtl
- parallel
- parsec
- pureMD5
- safe
executables:
  AOC:
    main: Main.hs
    ghc-options:
      - -ddump-to-file 
      - -ddump-hi
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -O2
    source-dirs:
      - src
data-dir: data
data-files:
  - '2023/*.input'
  - '2022/*.input'
  - '2021/*.input'
  - '2020/*.input'
  - '2019/*.input'
  - '2018/*.input'
  - '2017/*.input'
  - '2016/*.input'
  - '2015/*.input'
stability: experimental
